name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 21

    steps:
    - uses: actions/checkout@v7
    - name: set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v5
      with:
        distribution: 'oracle'
        java-version: ${{ env.JAVA_VERSION }}
